//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by TerraEd.rc
//
#define IDD_ABOUTBOX                    100
#define CG_IDD_PAINTBAR                 102
#define CG_IDD_PALETTE                  103
#define CG_ID_VIEW_PAINTBAR             104
#define IDR_MAINFRAME                   128
#define IDR_TERRAETYPE                  129
#define IDB_EDIT_ICONS                  130
#define IDR_OBJ_POPUP                   132
#define IDD_EDIT_LEVEL                  133
#define IDD_EDIT_TEXTURE                134
#define IDD_EDIT_OBJECT                 135
#define IDD_EDIT_EVENT                  136
#define IDD_EDIT_SPRITE                 137
#define IDD_EDIT_OBJECT_DATA            138
#define IDD_EDIT_SPRITE_DATA            139
#define IDC_CURSOR_ZOOM                 141
#define IDC_CURSOR_PAN_SEL              142
#define IDC_CURSOR_PAN                  143
#define IDD_SELECTDEVICE                144
#define IDC_CURSOR_ROTATE               144
#define IDD_RANDOM_OBJ                  145
#define IDD_SELECT_OBJ                  146
#define IDD_FILL_DLG                    148
#define IDD_DELETE_FILES                150
#define IDD_ADD_TEXTURE                 152
#define IDC_DEVICE_COMBO                1000
#define IDC_LEVEL_TREE                  1000
#define IDC_TIMER                       1001
#define IDC_SPRITE_TREE                 1001
#define IDC_BASE_TEXTURE                1002
#define IDC_ADAPTER_COMBO               1002
#define IDC_OBJECTS_TREE                1002
#define IDC_TC_FILE                     1003
#define IDC_FULLSCREENMODES_COMBO       1003
#define IDC_WEAPONS_TREE                1003
#define IDC_TC_SCALE                    1004
#define IDC_MESSAGE                     1005
#define IDC_AL_FILE                     1005
#define IDC_MULTISAMPLE_COMBO           1005
#define IDC_AL_SCALE                    1006
#define IDC_TYPE                        1007
#define IDC_POS_X                       1008
#define IDC_PU_TYPE                     1008
#define IDC_GAME_STATE                  1008
#define IDC_POS_Y                       1009
#define IDC_POS_Z                       1010
#define IDC_NAME                        1011
#define IDC_TEAM                        1012
#define IDC_SUN_POS_X                   1012
#define IDC_GOAL                        1013
#define IDC_SUN_POS_Y                   1013
#define IDC_SPIN1                       1014
#define IDC_RESP_NAME                   1014
#define IDC_AI                          1015
#define IDC_SPIN2                       1015
#define IDC_ACTIVATE_EVENT              1015
#define IDC_SPIN3                       1016
#define IDC_WINDOW                      1016
#define IDC_DISCRIPTION                 1017
#define IDC_HIGHTMAP                    1018
#define IDC_FULLSCREEN                  1018
#define IDC_T_SKY                       1019
#define IDC_T_GROUND                    1020
#define IDC_T_WATER1                    1021
#define IDC_T_WATER2                    1022
#define IDC_SHOW_SKY_BOX                1024
#define IDC_SHOW_WATER                  1025
#define IDC_BG_COLOUR                   1026
#define IDC_COLOUR                      1027
#define IDC_FOG_START                   1028
#define IDC_FOG_END                     1029
#define IDC_WATER_LEVEL                 1030
#define IDC_MAP_HIGHT                   1031
#define IDC_MAP_SCALE                   1033
#define IDC_SPIN5                       1034
#define IDC_SPIN6                       1035
#define IDC_TAB1                        1035
#define IDC_SPIN7                       1036
#define IDC_SPIN8                       1037
#define IDC_HM_FILE                     1038
#define IDC_SKY_FILE                    1039
#define IDC_GROUND_FILE                 1040
#define IDC_AL_FILE_BUT                 1040
#define IDC_WATER1_FILE                 1041
#define IDC_TC_FILE_BUT                 1041
#define IDC_WATER2_FILE                 1042
#define IDC_FILE                        1043
#define IDC_SUN_POS_Z                   1043
#define IDC_SHADOW                      1044
#define IDC_SCALE                       1045
#define IDC_X_SIZE                      1046
#define IDC_ROT_Z                       1046
#define IDC_Y_SIZE                      1047
#define IDC_ROT_Y                       1047
#define IDC_MIN_SPEED                   1048
#define IDC_PU_DURATION                 1049
#define IDC_MAX_SPEED                   1049
#define IDC_ACCEL                       1050
#define IDC_STATS_WP                    1051
#define IDC_TURN                        1051
#define IDC_STATS_H                     1052
#define IDC_DRAG                        1052
#define IDC_STATS_S                     1053
#define IDC_MIN_HIGHT                   1053
#define IDC_STATS_MS                    1054
#define IDC_MAX_HIGHT                   1054
#define IDC_FILE_BUT                    1055
#define IDC_PERCENT                     1055
#define IDC_REST_ROT                    1057
#define IDC_BUILDING                    1058
#define IDC_USER                        1059
#define IDC_SHIELDS                     1060
#define IDC_HEALTH                      1061
#define IDC_REGEN                       1062
#define IDC_WEAPON_TYPE                 1063
#define IDC_NUMB_ITEMS                  1064
#define IDC_OBJECTS                     1067
#define IDC_ADD                         1068
#define IDC_REMOVE                      1069
#define IDC_USE_POINT                   1073
#define IDC_X                           1074
#define IDC_Y                           1075
#define IDC_RAD                         1076
#define IDC_GENERATE_LIGHT              1079
#define IDC_BRUSH                       1080
#define IDC_BRUSH_TEXTURE               1081
#define IDC_TEXTURE                     1081
#define IDC_LIST1                       1085
#define IDC_ACTIVE                      1087
#define IDC_OBJ_NAME                    1092
#define IDC_VISABLE                     1093
#define IDC_ADD_TEXTURE                 1094
#define IDC_REMOVE_TEXTURE              1095
#define IDC_TEXTURES                    1096
#define IDC_TEXTURE_FILE                1097
#define ID_DELETE                       32772
#define ID_EDIT                         32773
#define ID_LEVEL_ADD_TEXTURE            32774
#define ID_LEVEL_ADD_SPRITE             32775
#define ID_LEVEL_ADD_OBJECT             32776
#define ID_LEVEL_ADD_EVENT              32777
#define ID_EVENT_ADD_CREATEOBJECT       32778
#define ID_EVENT_ADD_CREATESPRITE       32779
#define ID_EVENT_ADD_CHANGESPRITE       32780
#define ID_TOOLS_NEW_LEVEL              32784
#define ID_LEVEL_ACTIVE                 32785
#define ID_TOOLS_NEW_OBJECTDATA         32786
#define ID_TOOLS_NEW_SPRITEDATA         32787
#define ID_ROTATE_WORLD                 32788
#define ID_PAN_MODE                     32789
#define ID_SELECT_MODE                  32790
#define ID_ROTATE_SELECTED              32791
#define ID_TOOLS_CREATERANDOMOBJECTS    32792
#define ID_TOOLS_GENERATELIGHTMAP       32793
#define ID_PAINT_MODE                   32794
#define ID_EDIT_TERRAIN                 32795
#define ID_FILE_SAVECURRENTTERRAIN      32797
#define ID_FILE_SAVETEXTURES            32798
#define ID_VIEW_FOG                     32799
#define ID_TOOLS_FILL                   32800
#define ID_TOOLS_ADDFILE                32801
#define ID_TOOLS_REMOVEFILE             32802
#define ID_EVENT_DISPLAY                32803
#define ID_SPRITE_VIEW                  32804

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        153
#define _APS_NEXT_COMMAND_VALUE         32805
#define _APS_NEXT_CONTROL_VALUE         1098
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
